/**
 * Streaming Validation Loop Pattern - Fixture Data
 *
 * This file contains mock data for the budget allocation demo scenario.
 * All data is deterministic and version-controlled for consistent demos.
 *
 * @pattern Streaming Validation Loop
 * @scenario StreamFlow PM Q1 budget allocation across engineering teams
 */

import type { BudgetAllocation, StreamEvent } from './types';

/**
 * Default budget allocations proposed by the AI.
 *
 * Educational Note: These represent the AI's initial recommendations before
 * user approval. In a real system, these would be generated by an LLM based
 * on historical data, team velocity, and strategic priorities.
 */
export const defaultAllocations: BudgetAllocation[] = [
  {
    team: 'Frontend',
    budget: 250000,
    headcount: 4,
    contractors: 1,
    rationale:
      'Frontend team needs additional headcount to deliver the new React dashboard redesign and streaming UX features.',
  },
  {
    team: 'Backend',
    budget: 300000,
    headcount: 5,
    contractors: 0,
    rationale:
      'Backend team requires increased investment for infrastructure scaling and real-time streaming API development.',
  },
  {
    team: 'Mobile',
    budget: 200000,
    headcount: 3,
    contractors: 2,
    rationale:
      'Mobile team transitioning to React Native requires contractor support during migration while maintaining existing apps.',
  },
  {
    team: 'Platform',
    budget: 350000,
    headcount: 6,
    contractors: 0,
    rationale:
      'Platform team is critical for DevOps, CI/CD, and infrastructure reliability. Requires senior-level hires.',
  },
];

/**
 * Budget analysis text for each team (streamed before checkpoint).
 *
 * Educational Note: This analysis provides context for the proposed allocations.
 * It demonstrates streaming text before pausing for user approval.
 */
export const budgetAnalyses: Record<string, string> = {
  Frontend: `Analyzing Frontend team budget requirements...

Current team: 3 FTEs, 0 contractors
Planned initiatives: Dashboard redesign, streaming UX library, mobile web optimization
Historical velocity: 45 story points/sprint
Projected needs: +1 FTE (Senior React), +1 contractor (UX designer)

Recommended allocation: $250,000
- Base salaries: $180,000
- Contractor costs: $40,000
- Tools & licenses: $15,000
- Training & conferences: $15,000`,

  Backend: `Analyzing Backend team budget requirements...

Current team: 4 FTEs, 0 contractors
Planned initiatives: Real-time streaming APIs, GraphQL federation, observability upgrades
Historical velocity: 52 story points/sprint
Projected needs: +1 FTE (Staff Engineer - streaming expertise)

Recommended allocation: $300,000
- Base salaries: $220,000
- Infrastructure costs: $45,000
- Tools & licenses: $20,000
- Training & conferences: $15,000`,

  Mobile: `Analyzing Mobile team budget requirements...

Current team: 3 FTEs, 0 contractors
Planned initiatives: React Native migration, iOS app rewrite, Android feature parity
Historical velocity: 38 story points/sprint
Projected needs: +0 FTEs (retain current team), +2 contractors (RN specialists for migration)

Recommended allocation: $200,000
- Base salaries: $135,000
- Contractor costs: $45,000
- App store fees: $5,000
- Tools & licenses: $10,000
- Training & conferences: $5,000`,

  Platform: `Analyzing Platform team budget requirements...

Current team: 5 FTEs, 0 contractors
Planned initiatives: Kubernetes migration, observability stack, multi-region deployment
Historical velocity: 48 story points/sprint
Projected needs: +1 FTE (Senior DevOps), maintain current team

Recommended allocation: $350,000
- Base salaries: $270,000
- Cloud infrastructure: $50,000
- Tools & licenses: $20,000
- Training & conferences: $10,000`,
};

/**
 * Complete stream event sequence for the budget allocation demo.
 *
 * Educational Note: This fixture demonstrates the full checkpoint lifecycle:
 * 1. Stream budget analysis for each team
 * 2. Pause at checkpoint (wait for approval)
 * 3. Resume after user response
 * 4. Repeat for each team
 * 5. Emit final plan
 *
 * The actual stream generator in mockStream.ts will inject user responses
 * at runtime based on user actions in the UI.
 */
export const budgetAllocationStreamFixture: Omit<StreamEvent, 'timestamp'>[] = [
  // Team 1: Frontend
  {
    type: 'budget_analysis',
    data: {
      team: 'Frontend',
      analysis: budgetAnalyses.Frontend,
    },
  },
  {
    type: 'checkpoint',
    data: {
      checkpointId: 'checkpoint-frontend',
      phase: 'waiting_for_approval',
      question: 'Approve $250,000 allocation to Frontend team?',
      proposedValue: defaultAllocations[0],
      actions: ['approve', 'edit', 'skip'],
      timeoutMs: 30000, // 30 seconds
    },
  },
  // Note: checkpoint_response and checkpoint_resume are injected at runtime

  // Team 2: Backend
  {
    type: 'budget_analysis',
    data: {
      team: 'Backend',
      analysis: budgetAnalyses.Backend,
    },
  },
  {
    type: 'checkpoint',
    data: {
      checkpointId: 'checkpoint-backend',
      phase: 'waiting_for_approval',
      question: 'Approve $300,000 allocation to Backend team?',
      proposedValue: defaultAllocations[1],
      actions: ['approve', 'edit', 'skip'],
      timeoutMs: 30000,
    },
  },

  // Team 3: Mobile
  {
    type: 'budget_analysis',
    data: {
      team: 'Mobile',
      analysis: budgetAnalyses.Mobile,
    },
  },
  {
    type: 'checkpoint',
    data: {
      checkpointId: 'checkpoint-mobile',
      phase: 'waiting_for_approval',
      question: 'Approve $200,000 allocation to Mobile team?',
      proposedValue: defaultAllocations[2],
      actions: ['approve', 'edit', 'skip'],
      timeoutMs: 30000,
    },
  },

  // Team 4: Platform
  {
    type: 'budget_analysis',
    data: {
      team: 'Platform',
      analysis: budgetAnalyses.Platform,
    },
  },
  {
    type: 'checkpoint',
    data: {
      checkpointId: 'checkpoint-platform',
      phase: 'waiting_for_approval',
      question: 'Approve $350,000 allocation to Platform team?',
      proposedValue: defaultAllocations[3],
      actions: ['approve', 'edit', 'skip'],
      timeoutMs: 30000,
    },
  },

  // Final plan (emitted after all checkpoints resolved)
  {
    type: 'final_plan',
    data: {
      allocations: defaultAllocations,
      totalBudget: defaultAllocations.reduce((sum, a) => sum + a.budget, 0),
      summary: `Q1 Budget Allocation Plan - Approved

Total Budget: $1,100,000

Team Breakdown:
- Frontend: $250,000 (4 FTEs, 1 contractor)
- Backend: $300,000 (5 FTEs, 0 contractors)
- Mobile: $200,000 (3 FTEs, 2 contractors)
- Platform: $350,000 (6 FTEs, 0 contractors)

Total Headcount: 18 FTEs, 3 contractors

Key Investments:
- React dashboard redesign and streaming UX library (Frontend)
- Real-time streaming APIs and GraphQL federation (Backend)
- React Native migration for cross-platform consistency (Mobile)
- Kubernetes migration and multi-region deployment (Platform)

All allocations have been approved by the Product Manager.
Budget is aligned with Q1 strategic priorities and roadmap commitments.`,
    },
  },
];

/**
 * Fast-mode fixture for testing (reduced delays).
 *
 * Educational Note: Tests should run quickly. This fixture uses the same
 * events but with minimal delays for fast test execution.
 */
export const fastModeStreamFixture = budgetAllocationStreamFixture.map(
  (event) => ({
    ...event,
    // Fast mode: reduce all timeouts to 1 second
    ...(event.type === 'checkpoint'
      ? { data: { ...event.data, timeoutMs: 1000 } }
      : {}),
  })
);

/**
 * Default fallback allocation for skipped checkpoints.
 *
 * Educational Note: When a user skips a checkpoint, we need a fallback value.
 * In this demo, the fallback is $0 (team receives no budget).
 */
export function getDefaultAllocation(team: string): BudgetAllocation {
  return {
    team,
    budget: 0,
    headcount: 0,
    contractors: 0,
    rationale: `Budget allocation skipped by user. Team ${team} receives no allocation for Q1.`,
  };
}
